# Generated by Django 4.2.3 on 2023-08-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerregister_tb',
            name='File',
            field=models.FileField(upload_to=''),
        ),
    ]
