# Generated by Django 4.2.3 on 2023-08-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0004_category_tb'),
        ('seller', '0002_alter_sellerregister_tb_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('File', models.FileField(upload_to='')),
                ('Price', models.CharField(max_length=20)),
                ('Stock', models.IntegerField()),
                ('Details', models.CharField(max_length=20)),
                ('Categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.category_tb')),
                ('Sellerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerregister_tb')),
            ],
        ),
    ]
