# Generated by Django 4.2.3 on 2023-08-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_tb',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='register_tb',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='register_tb',
            old_name='dateofbirth',
            new_name='Dateofbirth',
        ),
        migrations.RenameField(
            model_name='register_tb',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='register_tb',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='register_tb',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='register_tb',
            old_name='phonenumber',
            new_name='Phonenumber',
        ),
        migrations.RenameField(
            model_name='register_tb',
            old_name='username',
            new_name='Username',
        ),
    ]
