# Generated by Django 4.2.3 on 2023-08-20 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_product_tb'),
        ('buyer', '0002_rename_age_register_tb_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shippingaddress', models.CharField(max_length=20)),
                ('Quantity', models.CharField(max_length=20)),
                ('Total', models.CharField(max_length=20)),
                ('Buyerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.register_tb')),
                ('Productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product_tb')),
            ],
        ),
    ]
