# Generated by Django 4.2.3 on 2023-08-21 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_cart_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('Phonenumber', models.CharField(max_length=20)),
                ('Status', models.CharField(default='pending', max_length=20)),
                ('Orderdate', models.CharField(max_length=20)),
                ('Time', models.CharField(max_length=20)),
                ('Grandtotal', models.IntegerField()),
                ('Buyerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.register_tb')),
            ],
        ),
    ]
