# Generated by Django 4.2.3 on 2023-08-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_orderitem_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_tb',
            old_name='Name',
            new_name='Customername',
        ),
    ]
