# Generated by Django 4.2.3 on 2023-08-22 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_rename_name_order_tb_customername'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cardnumber', models.CharField(max_length=20)),
                ('CardholderName', models.CharField(max_length=20)),
                ('Expirtdate', models.CharField(max_length=20)),
                ('CVV', models.CharField(max_length=20)),
                ('Buyerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.register_tb')),
                ('Orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.order_tb')),
            ],
        ),
    ]
