# Generated by Django 4.2.3 on 2023-08-07 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0002_admin_tb_delete_register_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_tb',
            old_name='userame',
            new_name='username',
        ),
    ]
